# Generated by Django 4.2.1 on 2023-06-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0002_categoria_alter_video_descricao_video_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluraflix.categoria'),
        ),
    ]
