# Generated by Django 4.2.1 on 2023-06-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0008_video_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='free',
        ),
    ]
